package com.gambit.sdk.pubsub.exceptions;

/**
 * Represents an Exception generated by the Pub/Sub SDK.
 */
public class PubSubException extends Exception {
    /**
     * Creates an exception without a message.
     */
    public PubSubException() {
        super();
    }
    
    /**
     * Creates an exceptoin with the message given in {@code message}
     *
     * @param message Message that the PubSubException contains.
     */
    public PubSubException(String message) {
        super(message);
    }
}